input.onButtonPressed(Button.A, function () {
    robot.tourner_roue(Roue.Droite, Sens.Avant, 50)
    robot.tourner_roue(Roue.Gauche, Sens.Avant, 50)
    basic.pause(1000)
    robot.stop()
})
input.onLogoEvent(TouchButtonEvent.Pressed, function () {
    robot.deplacer(RobotDirection.Avant, 50)
    basic.pause(1000)
    robot.deplacer(RobotDirection.Droite, 50)
    basic.pause(500)
    robot.deplacer(RobotDirection.Avant, 50)
    basic.pause(1000)
    robot.deplacer(RobotDirection.Gauche, 50)
    basic.pause(500)
    robot.deplacer(RobotDirection.Arriere, 50)
    basic.pause(1000)
    robot.stop()
})
robot.configurer_roue(Roue.Gauche, AnalogPin.P3)
robot.configurer_roue(Roue.Droite, AnalogPin.P4)
